# Generated by Django 6.0.7 on 2026-08-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_business_user_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='business',
            name='nit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='sector',
            field=models.CharField(choices=[('tienda', 'Tiendas y comercios'), ('restaurante', 'Restaurantes'), ('servicios', 'Empresas de servicios'), ('manufactura', 'Producción y manufactura'), ('multi_sede', 'Empresas multi-sede'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
