# Generated by Django 5.2.17 on 2026-09-10 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_business_direccion_business_logo_business_nit_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="business",
            options={
                "ordering": ["name"],
                "verbose_name": "Negocio",
                "verbose_name_plural": "Negocios",
            },
        ),
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Empresa", "verbose_name_plural": "Empresas"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Usuario", "verbose_name_plural": "Usuarios"},
        ),
        migrations.AlterField(
            model_name="business",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="businesses",
                to="users.company",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="business",
            name="direccion",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Dirección"
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AlterField(
            model_name="business",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="logos/", verbose_name="Logo"
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nombre del negocio"),
        ),
        migrations.AlterField(
            model_name="business",
            name="nit",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="NIT"
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="sector",
            field=models.CharField(
                choices=[
                    ("tienda", "Tiendas y comercios"),
                    ("restaurante", "Restaurantes"),
                    ("servicios", "Empresas de servicios"),
                    ("manufactura", "Producción y manufactura"),
                    ("multi_sede", "Empresas multi-sede"),
                    ("otro", "Otro"),
                ],
                default="otro",
                max_length=20,
                verbose_name="Sector",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="telefono",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Teléfono"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Correo de contacto"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Teléfono de contacto"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creada el"),
        ),
        migrations.AlterField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activa"),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="company",
            name="tax_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="NIT"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="users.business",
                verbose_name="Negocio",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="users.company",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Teléfono"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Administrador"), ("employee", "Empleado")],
                default="employee",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
    ]
