# Generated by Django 5.2.17 on 2026-09-12 03:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0004_alter_business_options_alter_company_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Plan mensual",
                        max_length=100,
                        verbose_name="Nombre del plan",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor de la cuota",
                    ),
                ),
                (
                    "cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Mensual"),
                            ("quarterly", "Trimestral"),
                            ("yearly", "Anual"),
                        ],
                        default="monthly",
                        max_length=10,
                        verbose_name="Ciclo de cobro",
                    ),
                ),
                (
                    "billing_day",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Día del mes en que vence la cuota. Si el mes no lo tiene, se usa el último día.",
                        verbose_name="Día de corte",
                    ),
                ),
                (
                    "grace_days",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Días después del corte antes de bloquear la cuenta.",
                        verbose_name="Días de gracia",
                    ),
                ),
                (
                    "starts_on",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Inicio del cobro",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("trial", "En prueba"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "blocking_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Desactívalo para clientes a los que no quieres cortarles el servicio.",
                        verbose_name="Bloquear si no paga",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas internas")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan",
                        to="users.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de la empresa",
                "verbose_name_plural": "Planes de las empresas",
                "ordering": ["company__name"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Cubre desde")),
                ("period_end", models.DateField(verbose_name="Cubre hasta")),
                ("due_date", models.DateField(verbose_name="Se vence el")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("paid", "Pagada"),
                            ("void", "Anulada"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "paid_on",
                    models.DateField(blank=True, null=True, verbose_name="Pagada el"),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor pagado",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("transfer", "Transferencia"),
                            ("cash", "Efectivo"),
                            ("other", "Otro"),
                        ],
                        max_length=10,
                        verbose_name="Medio de pago",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Referencia"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creada el"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="billing.plan",
                        verbose_name="Plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuota",
                "verbose_name_plural": "Cuotas",
                "ordering": ["-period_start", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan", "period_start"),
                        name="uniq_invoice_period_per_plan",
                    )
                ],
            },
        ),
    ]
