# Generated by Django 5.2.17 on 2026-09-10 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_category_business"),
        ("users", "0004_alter_business_options_alter_company_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["type", "name"],
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="users.business",
                verbose_name="Negocio",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activa"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[("income", "Ingreso"), ("expense", "Egreso")],
                max_length=10,
                verbose_name="Tipo",
            ),
        ),
    ]
