# Generated by Django 5.2.17 on 2026-09-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplier",
            options={"ordering": ["name"]},
        ),
    ]
