# Generated by Django 5.2.17 on 2026-09-10 15:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_inventorymovement_options_and_more"),
        ("purchases", "0002_alter_supplier_options"),
        ("users", "0004_alter_business_options_alter_company_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseinvoice",
            options={
                "verbose_name": "Factura de compra",
                "verbose_name_plural": "Facturas de compra",
            },
        ),
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Orden de compra",
                "verbose_name_plural": "Órdenes de compra",
            },
        ),
        migrations.AlterModelOptions(
            name="purchaseorderline",
            options={
                "verbose_name": "Línea de la orden",
                "verbose_name_plural": "Líneas de la orden",
            },
        ),
        migrations.AlterModelOptions(
            name="purchasereceipt",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Recepción de mercancía",
                "verbose_name_plural": "Recepciones de mercancía",
            },
        ),
        migrations.AlterModelOptions(
            name="purchasereceiptline",
            options={
                "verbose_name": "Línea de recepción",
                "verbose_name_plural": "Líneas de recepción",
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "ordering": ["name"],
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
            },
        ),
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_invoices",
                to="users.business",
                verbose_name="Negocio",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creada el"),
        ),
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Registrada por",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="due_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de vencimiento"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="invoice_date",
            field=models.DateField(verbose_name="Fecha de la factura"),
        ),
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notas"),
        ),
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="number",
            field=models.CharField(max_length=100, verbose_name="Número de factura"),
        ),
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="purchases.purchaseorder",
                verbose_name="Orden de compra",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Subtotal"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="IVA"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="total",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Total"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_orders",
                to="users.business",
                verbose_name="Negocio",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creada el"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creada por",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Descuento"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="expected_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha estimada de entrega"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notas"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="number",
            field=models.CharField(
                editable=False, max_length=50, unique=True, verbose_name="Número"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Fecha de la orden"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador"),
                    ("sent", "Enviado"),
                    ("approved", "Aprobado"),
                    ("partial", "Parcial"),
                    ("received", "Recibido"),
                    ("cancelled", "Cancelado"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="purchases.supplier",
                verbose_name="Proveedor",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Porcentaje de impuesto sobre el subtotal",
                max_digits=5,
                verbose_name="IVA (%)",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizada el"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="inventory.warehouse",
                verbose_name="Bodega de destino",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="po_lines",
                to="inventory.product",
                verbose_name="Producto",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderline",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="purchases.purchaseorder",
                verbose_name="Orden de compra",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderline",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0.001)],
                verbose_name="Cantidad",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderline",
            name="received_qty",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=12,
                verbose_name="Cantidad recibida",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderline",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Precio unitario",
            ),
        ),
        migrations.AlterField(
            model_name="purchasereceipt",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_receipts",
                to="users.business",
                verbose_name="Negocio",
            ),
        ),
        migrations.AlterField(
            model_name="purchasereceipt",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creada el"),
        ),
        migrations.AlterField(
            model_name="purchasereceipt",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Registrada por",
            ),
        ),
        migrations.AlterField(
            model_name="purchasereceipt",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notas"),
        ),
        migrations.AlterField(
            model_name="purchasereceipt",
            name="number",
            field=models.CharField(
                editable=False, max_length=50, unique=True, verbose_name="Número"
            ),
        ),
        migrations.AlterField(
            model_name="purchasereceipt",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="purchases.purchaseorder",
                verbose_name="Orden de compra",
            ),
        ),
        migrations.AlterField(
            model_name="purchasereceipt",
            name="received_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Fecha de recepción"
            ),
        ),
        migrations.AlterField(
            model_name="purchasereceipt",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_receipts",
                to="inventory.warehouse",
                verbose_name="Bodega donde ingresa",
            ),
        ),
        migrations.AlterField(
            model_name="purchasereceiptline",
            name="order_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipt_lines",
                to="purchases.purchaseorderline",
                verbose_name="Línea de la orden",
            ),
        ),
        migrations.AlterField(
            model_name="purchasereceiptline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipt_lines",
                to="inventory.product",
                verbose_name="Producto",
            ),
        ),
        migrations.AlterField(
            model_name="purchasereceiptline",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0.001)],
                verbose_name="Cantidad recibida",
            ),
        ),
        migrations.AlterField(
            model_name="purchasereceiptline",
            name="receipt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="purchases.purchasereceipt",
                verbose_name="Recepción",
            ),
        ),
        migrations.AlterField(
            model_name="purchasereceiptline",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Costo unitario",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Dirección"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suppliers",
                to="users.business",
                verbose_name="Negocio",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ciudad"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Correo electrónico"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="contact_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Nombre del contacto"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="Teléfono"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(
                max_length=200, verbose_name="Nombre o razón social"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="nit",
            field=models.CharField(max_length=50, verbose_name="NIT"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notas"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="payment_terms",
            field=models.CharField(
                blank=True,
                help_text="Ej: 30 días, contado, 50% anticipado",
                max_length=100,
                verbose_name="Condiciones de pago",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
        ),
    ]
