# Generated by Django 5.2.17 on 2026-09-10 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_accounts", "0002_alter_bankaccount_options_and_more"),
        ("core", "0003_alter_category_options_alter_category_business_and_more"),
        ("incomes", "0002_income_business"),
        ("users", "0004_alter_business_options_alter_company_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="income",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Ingreso",
                "verbose_name_plural": "Ingresos",
            },
        ),
        migrations.AlterField(
            model_name="income",
            name="amount",
            field=models.DecimalField(
                decimal_places=0, max_digits=12, verbose_name="Monto"
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incomes",
                to="bank_accounts.bankaccount",
                verbose_name="Cuenta bancaria",
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incomes",
                to="users.business",
                verbose_name="Negocio",
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incomes",
                to="core.category",
                verbose_name="Categoría",
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateField(verbose_name="Fecha"),
        ),
        migrations.AlterField(
            model_name="income",
            name="description",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Descripción"
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Efectivo"),
                    ("transfer", "Transferencia"),
                    ("card", "Tarjeta"),
                ],
                max_length=10,
                verbose_name="Método de pago",
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incomes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Registrado por",
            ),
        ),
    ]
