# Generated by Django 5.2.17 on 2026-09-10 15:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("users", "0004_alter_business_options_alter_company_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventorymovement",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Movimiento de inventario",
                "verbose_name_plural": "Movimientos de inventario",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
            },
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Categoría de producto",
                "verbose_name_plural": "Categorías de producto",
            },
        ),
        migrations.AlterModelOptions(
            name="tenantsetup",
            options={
                "verbose_name": "Configuración inicial de inventario",
                "verbose_name_plural": "Configuraciones iniciales de inventario",
            },
        ),
        migrations.AlterModelOptions(
            name="unitofmeasure",
            options={
                "ordering": ["name"],
                "verbose_name": "Unidad de medida",
                "verbose_name_plural": "Unidades de medida",
            },
        ),
        migrations.AlterModelOptions(
            name="warehouse",
            options={
                "ordering": ["name"],
                "verbose_name": "Bodega",
                "verbose_name_plural": "Bodegas",
            },
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="balance",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=12,
                verbose_name="Saldo resultante",
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_movements",
                to="users.business",
                verbose_name="Negocio",
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Registrado por",
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="movement_type",
            field=models.CharField(
                choices=[("in", "Entrada"), ("out", "Salida"), ("adjust", "Ajuste")],
                max_length=10,
                verbose_name="Tipo de movimiento",
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="inventory.product",
                verbose_name="Producto",
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Cantidad",
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="reason",
            field=models.TextField(blank=True, verbose_name="Motivo"),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="reference",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Referencia"
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Costo unitario",
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.warehouse",
                verbose_name="Bodega",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="users.business",
                verbose_name="Negocio",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="inventory.productcategory",
                verbose_name="Categoría",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="product",
            name="current_stock",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Stock actual",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/", verbose_name="Imagen"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AlterField(
            model_name="product",
            name="min_stock",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Stock mínimo",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="product",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Precio de compra",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sale_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Precio de venta",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=50, verbose_name="Código (SKU)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="uom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="inventory.unitofmeasure",
                verbose_name="Unidad de medida",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inv_categories",
                to="users.business",
                verbose_name="Negocio",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activa"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="inventory.productcategory",
                verbose_name="Categoría padre",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsetup",
            name="business",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_setup",
                to="users.business",
                verbose_name="Negocio",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsetup",
            name="provisioned_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Configurado el"
            ),
        ),
        migrations.AlterField(
            model_name="unitofmeasure",
            name="abbreviation",
            field=models.CharField(max_length=10, verbose_name="Abreviatura"),
        ),
        migrations.AlterField(
            model_name="unitofmeasure",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uoms",
                to="users.business",
                verbose_name="Negocio",
            ),
        ),
        migrations.AlterField(
            model_name="unitofmeasure",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activa"),
        ),
        migrations.AlterField(
            model_name="unitofmeasure",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Dirección"
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warehouses",
                to="users.business",
                verbose_name="Negocio",
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="code",
            field=models.CharField(blank=True, max_length=30, verbose_name="Código"),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creada el"),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activa"),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="manager",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Responsable"
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notas"),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizada el"),
        ),
    ]
