# Generated by Django 5.2.17 on 2026-09-11 16:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("expenses", "0003_alter_expense_options_alter_expense_amount_and_more"),
        ("users", "0004_alter_business_options_alter_company_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Tipo de contrato"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "causes_social_benefits",
                    models.BooleanField(
                        default=True,
                        help_text="Desactívalo en contratos que no las generan, como prestación de servicios.",
                        verbose_name="Causa prestaciones sociales",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_types",
                        to="users.business",
                        verbose_name="Negocio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de contrato",
                "verbose_name_plural": "Tipos de contrato",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="users.business",
                        verbose_name="Negocio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="JobPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Nombre del cargo"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="users.business",
                        verbose_name="Negocio",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="positions",
                        to="payroll.department",
                        verbose_name="Departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="Nombres"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="Apellidos"),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de ciudadanía"),
                            ("CE", "Cédula de extranjería"),
                            ("PA", "Pasaporte"),
                            ("NIT", "NIT"),
                        ],
                        default="CC",
                        max_length=5,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "document",
                    models.CharField(max_length=30, verbose_name="Número de documento"),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Dirección"
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="Fecha de ingreso")),
                (
                    "termination_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de retiro"
                    ),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Salario base",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Activo"), ("inactive", "Retirado")],
                        default="active",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(blank=True, max_length=150, verbose_name="Banco"),
                ),
                (
                    "account_type",
                    models.CharField(
                        blank=True,
                        choices=[("savings", "Ahorros"), ("checking", "Corriente")],
                        max_length=10,
                        verbose_name="Tipo de cuenta",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número de cuenta"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observaciones")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="users.business",
                        verbose_name="Negocio",
                    ),
                ),
                (
                    "contract_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="payroll.contracttype",
                        verbose_name="Tipo de contrato",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="payroll.department",
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Opcional: enlaza al empleado con su usuario para que vea su desprendible.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario de Kivo",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="payroll.jobposition",
                        verbose_name="Cargo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="PayrollConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, verbose_name="Código")),
                ("name", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "kind",
                    models.CharField(
                        choices=[("earning", "Ingreso"), ("deduction", "Deducción")],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "calculation",
                    models.CharField(
                        choices=[
                            ("fixed", "Valor fijo"),
                            ("percent_base", "% del salario base del periodo"),
                            ("percent_earnings", "% del total devengado"),
                            ("manual", "Se digita en cada liquidación"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="Forma de cálculo",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="El monto si es valor fijo, o el porcentaje si se calcula sobre una base.",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor o porcentaje",
                    ),
                ),
                (
                    "applies_by_default",
                    models.BooleanField(
                        default=False,
                        help_text="Si está activo, entra en la liquidación de cada empleado sin digitarlo.",
                        verbose_name="Aplicar a todos automáticamente",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=100, verbose_name="Orden"),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_concepts",
                        to="users.business",
                        verbose_name="Negocio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Concepto de nómina",
                "verbose_name_plural": "Conceptos de nómina",
                "ordering": ["kind", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PayrollPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Nombre del periodo"),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Semanal"),
                            ("biweekly", "Quincenal"),
                            ("monthly", "Mensual"),
                            ("custom", "Personalizado"),
                        ],
                        default="biweekly",
                        max_length=10,
                        verbose_name="Frecuencia de pago",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha inicial")),
                ("end_date", models.DateField(verbose_name="Fecha final")),
                ("payment_date", models.DateField(verbose_name="Fecha de pago")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Abierto"),
                            ("processing", "En proceso"),
                            ("settled", "Liquidado"),
                            ("paid", "Pagado"),
                            ("closed", "Cerrado"),
                        ],
                        default="open",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "uses_social_benefits",
                    models.BooleanField(
                        default=False,
                        help_text="Prima, cesantías, intereses y vacaciones. Se calculan solas y no se descuentan al empleado: son costo adicional de la empresa.",
                        verbose_name="¿Causar prestaciones sociales en este periodo?",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "settled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Liquidado el"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Pagado el"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cerrado el"
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_periods",
                        to="users.business",
                        verbose_name="Negocio",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "payment_expense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payroll_periods",
                        to="expenses.expense",
                        verbose_name="Egreso del pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Periodo de nómina",
                "verbose_name_plural": "Periodos de nómina",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Salario base"
                    ),
                ),
                (
                    "worked_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Días trabajados",
                    ),
                ),
                (
                    "accrued_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Salario del periodo",
                    ),
                ),
                (
                    "total_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Total devengado",
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Total deducciones",
                    ),
                ),
                (
                    "net_pay",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Neto a pagar",
                    ),
                ),
                (
                    "social_benefits_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Prestaciones sociales",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observaciones")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="users.business",
                        verbose_name="Negocio",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payslips",
                        to="payroll.employee",
                        verbose_name="Empleado",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="payroll.payrollperiod",
                        verbose_name="Periodo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidación",
                "verbose_name_plural": "Liquidaciones",
                "ordering": ["employee__first_name", "employee__last_name"],
            },
        ),
        migrations.CreateModel(
            name="PayslipLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("earning", "Ingreso"),
                            ("deduction", "Deducción"),
                            ("benefit", "Prestación social"),
                        ],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Descripción"),
                ),
                (
                    "base",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Base del cálculo",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=7,
                        verbose_name="Porcentaje",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="Valor"
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lines",
                        to="payroll.payrollconcept",
                        verbose_name="Concepto",
                    ),
                ),
                (
                    "payslip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="payroll.payslip",
                        verbose_name="Liquidación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de la liquidación",
                "verbose_name_plural": "Líneas de la liquidación",
                "ordering": ["kind", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="contracttype",
            constraint=models.UniqueConstraint(
                fields=("business", "name"), name="uniq_contract_type_per_business"
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("business", "name"), name="uniq_department_per_business"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobposition",
            constraint=models.UniqueConstraint(
                fields=("business", "name"), name="uniq_position_per_business"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["business", "status"], name="payroll_emp_estado_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                fields=("business", "document"),
                name="uniq_employee_document_per_business",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollconcept",
            constraint=models.UniqueConstraint(
                fields=("business", "code"), name="uniq_concept_code_per_business"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollperiod",
            constraint=models.UniqueConstraint(
                fields=("business", "start_date", "end_date"),
                name="uniq_period_range_per_business",
            ),
        ),
        migrations.AddConstraint(
            model_name="payslip",
            constraint=models.UniqueConstraint(
                fields=("period", "employee"), name="uniq_payslip_per_period_employee"
            ),
        ),
    ]
