# Generated by Django 6.0.7 on 2026-08-27 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_business_user_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de la cuenta', max_length=150)),
                ('bank_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=50)),
                ('opening_balance', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva')], default='active', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='users.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
