# Generated by Django 5.2.17 on 2026-09-10 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_accounts", "0001_initial"),
        ("users", "0004_alter_business_options_alter_company_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bankaccount",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Cuenta bancaria",
                "verbose_name_plural": "Cuentas bancarias",
            },
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="account_number",
            field=models.CharField(max_length=50, verbose_name="Número de cuenta"),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_name",
            field=models.CharField(max_length=150, verbose_name="Banco"),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_accounts",
                to="users.business",
                verbose_name="Negocio",
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creada el"),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activa"),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="name",
            field=models.CharField(
                help_text="Nombre descriptivo de la cuenta",
                max_length=150,
                verbose_name="Nombre de la cuenta",
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="opening_balance",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="Saldo inicial"
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="status",
            field=models.CharField(
                choices=[("active", "Activa"), ("inactive", "Inactiva")],
                default="active",
                max_length=10,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizada el"),
        ),
    ]
