# Generated by Django 5.2.17 on 2026-09-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_accounts", "0002_alter_bankaccount_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bankaccount",
            options={
                "ordering": ["kind", "name"],
                "verbose_name": "Cuenta",
                "verbose_name_plural": "Cuentas",
            },
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="kind",
            field=models.CharField(
                choices=[("bank", "Cuenta bancaria"), ("cash", "Caja (efectivo)")],
                default="bank",
                help_text='Usa "Caja" para el efectivo que tienes en el negocio.',
                max_length=10,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="account_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Número de cuenta"
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Banco"),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="name",
            field=models.CharField(
                help_text='Cómo la reconoces: "Bancolombia ahorros", "Caja del mostrador"...',
                max_length=150,
                verbose_name="Nombre de la cuenta",
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="opening_balance",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Lo que tiene la cuenta en este momento. A partir de ahí Kivo suma los ingresos y resta los egresos que registres.",
                max_digits=12,
                verbose_name="Dinero que hay hoy",
            ),
        ),
    ]
